---
name: "Simple GithubAction Workflow"
on:
  push:
    branches:
    -main
    -master
    -production
jobs:

  job1:
    runs-on: ubuntu-24.04

    steps:
    - name: "Running Date Command"
      run: date
      shell: bash

    - name: "Getting OS Details"
      run: cat /etc/os-release
      shell: bash

    - name: "Current User Details"
      run: whoami
      shell: bash

    - name: "Current working Directory"
      run: |
        pwd
        ls -al
      shell: bash

    - name: "Checkout current Repository"
      uses: actions/checkout@v4

    - name: "Working Directory Details After Checkout"
      run: |
        pwd
        ls -al
      shell: bash

    - name: "Installing Terraform"
      run: |
        wget https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
        unzip terraform_1.12.2_linux_amd64.zip
        ./terraform version

    - name: "Running script.sh"
      run: |
       chmod +x script.sh
       ./script.sh


